name: 'wiz-cli'
on: [push, pull_request]

jobs:
  wiz-cli-iac-scan:
    name: 'Wiz-cli IaC Scan'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "templates/" # Set the relative path in the repo to scan
      POLICY: "chris-wang-se-iac" # Set the desired Wiz-cli policy to use
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Download Wiz-cli
      run: curl -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli
      
    - name: Print Wiz-cli version
      run: ./wizcli version
      
    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET" 
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
    
    - name: Run wiz-cli IaC scan
      run: ./wizcli iac scan --path $SCAN_PATH --policy $POLICY --tag owner=Chris-Wang-SE --tag repo=$GITHUB_REPOSITORY --tag run_id=$GITHUB_RUN_ID
